version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Publify
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/update_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
