AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PublifyWAFACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: 'PublifyWAFACL'
      Description: 'WAF rules for Publify'
      Scope: 'REGIONAL'
      DefaultAction:
        Allow: {}
      Rules:
        - Name: 'AWSManagedRulesCommonRuleSet'
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: 'AWSManagedRulesCommonRuleSetMetric'

        - Name: 'RateLimitRule'
          Priority: 2
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: 'IP'
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: 'RateLimitRule'
