apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: publify-cluster
  region: eu-north-1  # Votre région AWS actuelle

nodeGroups:
  - name: ng-1
    instanceType: t3.small  # Instance plus petite et moins chère que t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    labels: {role: worker}
    privateNetworking: true
