apiVersion: apps/v1
kind: Deployment
metadata:
  name: publify-app
spec:
  replicas: 2  # Démarrez avec 2 replicas
  selector:
    matchLabels:
      app: publify
  template:
    metadata:
      labels:
        app: publify
    spec:
      containers:
      - name: publify
        image: publify:latest
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: publify-secrets
                key: database-url
        resources:
          requests:
            memory: "128Mi"  # Valeurs plus modestes pour commencer
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
